version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    allow:
      - dependency-name: "all"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
    versioning-strategy: auto
    target-branch: "main"
    rebase-strategy: "auto"