root = "."
testdata_dir = "testdata"
tmp_dir = "dist"

[build]
  args_bin = []
  bin = "./dist/go_news_api"
  cmd = "go build -o ./dist/go_news_api -ldflags='-w -s' ."
  delay = 1000
  exclude_dir = ["assets", "dist", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  # full_bin = "GIN_MODE=release ./dist/go_news_api"
  full_bin = "GIN_MODE=debug ./dist/go_news_api"
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = ["go mod tidy"]
  # pre_cmd = ["export GIN_MODE=release", "go mod tidy"]
  # pre_cmd = ["export GIN_MODE=debug", "go mod tidy"]
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = true

[misc]
  clean_on_exit = true

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true