name: automerge

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - unlabeled
      - labeled
  push:
    branches:
      - main
  issue_comment:
    types:
      - created
  workflow_dispatch:

jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.16.3"
        env:
          GITHUB_TOKEN: "${{ secrets.PAT }}"
          LOG: "DEBUG"
          MERGE_LABELS: "automerge"
          MERGE_REMOVE_LABELS: "automerge"
          MERGE_METHOD: "merge"
          MERGE_REQUIRED_APPROVALS: "0"
          MERGE_DELETE_BRANCH: "true"
          MERGE_COMMIT_MESSAGE: "Auto merge PR #{pullRequest.number}: {pullRequest.title}|{pullRequest.description}"
          MERGE_FORKS: "true"
          MERGE_RETRIES: "1"
          MERGE_RETRY_SLEEP: "5000"
          UPDATE_LABELS: "automerge"
          UPDATE_METHOD: "merge"