name: Create Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version_bump:
        description: 'Version bump type (major, minor, patch)'
        required: true
        default: 'patch'
        type: choice
        options:
        - major
        - minor
        - patch

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.PAT }}

    - name: Fetch all tags
      run: git fetch --tags

    - name: Display go.mod
      run: cat go.mod

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.x'

    - name: Print Go version
      run: go version

    - name: Build for multiple platforms
      run: |
        mkdir -p build
        GOOS=linux GOARCH=amd64 go build -v -o build/go_news_api_linux_amd64 .
        GOOS=darwin GOARCH=amd64 go build -v -o build/go_news_api_darwin_amd64 .
        GOOS=windows GOARCH=amd64 go build -v -o build/go_news_api_windows_amd64.exe .
        GOOS=darwin GOARCH=arm64 go build -v -o build/go_news_api_darwin_arm64 .
        GOOS=linux GOARCH=arm64 go build -v -o build/go_news_api_linux_arm64 .
        
    - name: Bump version and push tag
      id: tag_version
      uses: anothrNick/github-tag-action@1.61.0
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
        DEFAULT_BUMP: ${{ github.event.inputs.version_bump || 'patch' }}
        WITH_V: true

    - name: Generate changelog
      id: changelog
      uses: mikepenz/release-changelog-builder-action@v3
      with:
        configuration: "changelog-config.json"
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.changelog.outputs.changelog }}
        draft: false
        prerelease: false
        files: |
          build/go_news_api_linux_amd64
          build/go_news_api_darwin_amd64
          build/go_news_api_windows_amd64.exe
          build/go_news_api_darwin_arm64
          build/go_news_api_linux_arm64
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}