name: Generate Changelog

on:
  push:
    branches:
      - main

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Generate Changelog
      uses: heinrichreimer/action-github-changelog-generator@v2.4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        output: CHANGELOG.md
        issues: true
        issuesWoLabels: true
        pullRequests: true
        prWoLabels: true
        unreleased: true
        compareLink: true
        excludeLabels: duplicate,question,invalid,wontfix
    - name: Commit Changelog
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update CHANGELOG.md
        file_pattern: CHANGELOG.md