name: go-news-api-continuous-integration
on:
  push:
    branches:
      - main
jobs:
  build-and-restart-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.5'
      
      - name: Run build script
        run: |
          rm -rf dist
          mkdir dist
          chmod +x ./build.sh
          ./build.sh
    
      - name: Deploy and Restart Service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /root/go_news_api
            git pull origin main
            sudo systemctl stop go_news_api.service
            rm -rf dist
            mkdir dist
            chmod +x ./build.sh
            ./build.sh
            scp -r ${{ github.workspace }}/dist/* .
            sudo systemctl start go_news_api.service

  check-service:
    runs-on: ubuntu-latest
    needs: build-and-restart-service
    steps:
      - name: Check service status
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            max_retries=5
            retry_count=0
            while [ $retry_count -lt $max_retries ]; do
              if sudo systemctl is-active --quiet go_news_api.service; then
                echo "Service is active."
                exit 0
              else
                echo "Service is not active. Attempt $((retry_count + 1)) of $max_retries."
                sleep 30
                retry_count=$((retry_count + 1))
              fi
            done
            echo "Service failed to become active after $max_retries attempts. Failing the workflow."
            exit 1

  check-endpoints:
    runs-on: ubuntu-latest
    needs: check-service
    steps:
      - name: Check /health endpoint
        run: |
          max_retries=5
          retry_count=0
          while [ $retry_count -lt $max_retries ]; do
            response=$(curl -s -o /dev/null -w "%{http_code}" https://news.tadeasfort.cz/health)
            if [ $response -eq 200 ]; then
              echo "Health check passed with status code $response"
              exit 0
            else
              echo "Health check failed with status code $response. Attempt $((retry_count + 1)) of $max_retries."
              sleep 30
              retry_count=$((retry_count + 1))
            fi
          done
          echo "Health check failed after $max_retries attempts. Last status code: $response"
          exit 1
      

  finish-workflow:
    runs-on: ubuntu-latest
    needs: check-endpoints
    steps:
      - name: Finish workflow
        run: echo "Deployment and tests completed successfully"